openapi: 3.0.1
info:
  title: JBox Standard Security API
  version: "@version@"
servers:
  - url: http://127.0.0.1:8080
    description: local

security:
  - bearerAuth: []

paths:
  /users:
    post:
      tags:
        - users
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/User"
        '400':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '401':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '403':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '500':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"

    put:
      tags:
        - users
      operationId: updateUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/User"
        '400':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '401':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '403':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '500':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"

  /users/filter:
    post:
      tags:
        - users
      operationId: filterUsers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./components_query.yaml#/components/schemas/PagingFilter"
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/PaginatedUsers'
        '400':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '401':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '403':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '404':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '500':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"

  /users/{id}:
    get:
      tags:
        - users
      operationId: getUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: "./components_common.yaml#/components/schemas/Uuid"
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/User"
        '400':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '401':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '403':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '500':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
    delete:
      tags:
        - users
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: "./components_common.yaml#/components/schemas/Uuid"
      responses:
        '204':
          description: No Content
        '400':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '401':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '403':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '500':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"

  /users/{id}/roles:
    get:
      tags:
        - users
      operationId: getRolesOfUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: "./components_common.yaml#/components/schemas/Uuid"
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PaginatedRoles"
        '400':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '401':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '403':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '500':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"

  /users/{id}/permissions:
    get:
      tags:
        - users
      operationId: getPermissionsOfUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: "./components_common.yaml#/components/schemas/Uuid"
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PaginatedUsers"
        '400':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '401':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '403':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '500':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"

  /roles/filter:
    post:
      tags:
        - roles
      operationId: filterRoles
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./components_query.yaml#/components/schemas/PagingFilter"
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/PaginatedRoles'
        '400':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '401':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '403':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '404':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '500':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"

  /roles/{id}:
    get:
      tags:
        - roles
      operationId: getRole
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: "./components_common.yaml#/components/schemas/Uuid"
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/Role"
        '400':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '401':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '403':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '500':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"

  /roles/{id}/users:
    get:
      tags:
        - roles
      operationId: getUsersOfRole
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: "./components_common.yaml#/components/schemas/Uuid"
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PaginatedUsers"
        '400':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '401':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '403':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '500':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"

  /roles/{id}/permissions:
    get:
      tags:
        - permissions
      operationId: getPermissionsOfRole
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: "./components_common.yaml#/components/schemas/Uuid"
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PaginatedPermissions"
        '400':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '401':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '403':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '500':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"

  /permissions/filter:
    post:
      tags:
        - permissions
      operationId: filterPermissions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./components_query.yaml#/components/schemas/PagingFilter"
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/PaginatedPermissions'
        '400':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '401':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '403':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '404':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '500':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"

  /permissions/{id}:
    get:
      tags:
        - permissions
      operationId: getPermission
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: "./components_common.yaml#/components/schemas/Uuid"
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/Permission"
        '400':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '401':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '403':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '500':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"

  /permissions/{id}/roles:
    get:
      tags:
        - permissions
      operationId: getRolesOfPermission
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: "./components_common.yaml#/components/schemas/Uuid"
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PaginatedRoles"
        '400':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '401':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '403':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '500':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"

  /permissions/{id}/users:
    get:
      tags:
        - permissions
      operationId: getUsersOfPermission
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: "./components_common.yaml#/components/schemas/Uuid"
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PaginatedUsers"
        '400':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '401':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '403':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"
        '500':
          $ref: "./components_error.yaml#/components/responses/ErrorResponse"

components:
  securitySchemes:
    bearerAuth:
      $ref: "./components_security.yaml#/components/securitySchemes/bearerAuth"

  schemas:
    User:
      type: object
      properties:
        uuid:
          $ref: "./components_common.yaml#/components/schemas/Uuid"
        name:
          type: string

    PaginatedUsers:
      allOf:     # Combines the BasicErrorModel and the inline model
        - $ref: './components_query.yaml#/components/schemas/Pagination'
        - type: object
          properties:
            content:
              type: array
              items:
                $ref: '#/components/schemas/User'

    Role:
      type: object
      properties:
        uuid:
          $ref: "./components_common.yaml#/components/schemas/Uuid"
        name:
          type: string

    PaginatedRoles:
      allOf:     # Combines the BasicErrorModel and the inline model
        - $ref: './components_query.yaml#/components/schemas/Pagination'
        - type: object
          properties:
            content:
              type: array
              items:
                $ref: '#/components/schemas/Role'

    Permission:
      type: object
      properties:
        uuid:
          $ref: "./components_common.yaml#/components/schemas/Uuid"
        name:
          type: string


    PaginatedPermissions:
      allOf:     # Combines the BasicErrorModel and the inline model
        - $ref: './components_query.yaml#/components/schemas/Pagination'
        - type: object
          properties:
            content:
              type: array
              items:
                $ref: '#/components/schemas/Permission'

