openapi: "3.1.0"
info:
  title: JBox Standard Query Api Components
  version: "$version@"

components:
  schemas:

    Pageable:
      type: object
      properties:
        offset:
          type: integer
          format: int64
        sort:
          $ref: '#/components/schemas/Sort'
        pageNumber:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        paged:
          type: boolean
        unpaged:
          type: boolean

    SortRequest:
      type: object
      required:
        - sortBy
      properties:
        sortBy:
          type: array
          items:
            $ref: '#/components/schemas/SortBy'

    PageRequest:
      type: object
      required:
        - pageNumber
        - pageSize
      properties:
        pageNumber:
          type: integer
          format: int32
          minimum: 0
          default: 0
        pageSize:
          type: integer
          format: int32
          minimum: 1
          maximum: 250

    Sort:
      type: object
      properties:
        empty:
          type: boolean
        sorted:
          type: boolean
        unsorted:
          type: boolean


    SortBy:
      type: object
      required:
        - field
        - order
      properties:
        sortField:
          type: string
        sortOrder:
          type: string
          default: "ASC"
          enum:
            - ASC
            - DESC

    PagingFilter:
      type: object
      properties:
        filter:
          $ref: '#/components/schemas/Filter'
        pageRequest:
          $ref: '#/components/schemas/PageRequest'
        sortRequest:
          $ref: '#/components/schemas/SortRequest'

    Filter:
      type: object
      properties:
        fieldFilters:
          type: array
          items:
            $ref: '#/components/schemas/FieldFilter'

    FieldFilter:
      type: object
      required:
        - field
      properties:
        field:
          type: string
        value:
          type: string

    Pagination:
      type: object
      properties:
        totalPages:
          type: integer
          format: int32
        totalElements:
          type: integer
          format: int64
        pageSize:
          type: integer
          format: int32
        pageNumber:
          type: integer
          format: int32
        first:
          type: boolean
        last:
          type: boolean
        numberOfElements:
          type: integer
          format: int32
        empty:
          type: boolean
        content:
          type: array
          items:
            type: object
