openapi: "3.1.0"
info:
  title: JBox Standard Security Components
  version: "$version@"

components:
  schemas:

    Uuid:
      type: string
      format: uuid
      pattern: '^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$'
