
SERVER_PORT: 8080
ACTUATOR_PORT: 8081
SERVER_MAX_HEADER_SIZE: 12KB
ENCODING_THRESHOLD: 200

DB_USER: admin
DB_PASSWORD: admin123
POSTGRES_BASE_URL: mapping-service-db
POSTGRES_PORT: 5432
POSTGRES_DB: oneid-local

# TODO: option to switch off security in docker
AAD_TENANT_ID: 659c3a90-ec90-4772-b772-cebe2050a82e
AAD_APP_CLIENT_ID: 6698b888-cc28-42db-b6f2-7ad68f62c9f6

BLOB_ENDPOINT: https://azurite:10000/devstoreaccount1
BLOB_CONTAINER_NAME: mappingservice

ADDRESS_VALIDATION_ORG_UNIT: 11487
ADDRESS_VALIDATION_TENANT_NAME: "Arvato_Germany"
ADDRESS_VALIDATION_CLIENT_ID: "47b3e024-64e1-4fb6-8f89-08377c5728e0"
ADDRESS_VALIDATION_CLIENT_SECRET: "c#bza0F(F4oYYgj)"
ADDRESS_VALIDATION_URL: "https://cloud.uipath.com"

LICENSE_VALIDATION_URL: "https://ocidvision.apps-test.arvato-scs.digital"
LICENSE_VALIDATION_USERNAME: "ocid"
LICENSE_VALIDATION_PASSWORD: "o7dgvHF6fhiASs7oE0vbHb06nwnA5exb"

MEDIVERSE_URL: "https://mediverse--b2bdev2.sandbox.my.salesforce.com/services/data"
MEDIVERSE_USERNAME: arvato.integration@arvato.com.b2bdev2
MEDIVERSE_PASSWORD: TelePort404#TJop1iPD7JIE84lAnnh4otvYM
MEDIVERSE_TOKEN_URI: "https://test.salesforce.com/services/oauth2/token"
MEDIVERSE_AUTHORIZE_URI: "https://test.salesforce.com/services/oauth2/authorize"
MEDIVERSE_CLIENT_ID: 3MVG954MqIw6FnnPdRJ8vKy.OEyGXgOnsVtqn7X6Y.1f5b9Vir5r.tuHYo_3YMCClXSfuFNPRXmZczmgUgBju
MEDIVERSE_CLIENT_SECRET: 207FD03767D206A79FB780D74F75630F89D1E21FBC33C5C0CE86CC49DC911D4F

SAP_URL: http://localhost:8080
SAP_ENV: dev
SAP_USERNAME: sapUser
SAP_PASSWORD: sapPassword

SFTP_HOST: localhost
SFTP_DDS_PATH: gi6/MEDIVERSE_BP.CSV
SFTP_PORT: 2222
SFTP_USER: client
SFTP_PASSWORT: client123

BASE_URL: localhost:4200

FEIGN_LOG_LEVEL: FULL

IMPORT_MEDIVERSE_CRON: "-"
IMPORT_OTSUKA_CRON: "-"
IMPORT_BIONTECH_CRON: "-"
