spring:
  datasource:
    url: jdbc:sqlserver://172.16.200.70:1433;database=EntsoMavir;encrypt=false;
    username: trenden
    # TODO: move to vault or k8s env var
    password: SokjurWit9

gelf:
  udp:
    host: 172.23.211.60
    port: 12201 # default GELF port of GELF Input App in Seq