ACTUATOR_PORT: 8081
DB_USER: admin
DB_PASSWORD: admin123
MAX_FILE_SIZE: 10MB
MAX_REQUEST_SIZE: 128MB
POSTGRES_BASE_URL: localhost
POSTGRES_PORT: 5432
POSTGRES_DB: backend
SERVER_MAX_HEADER_SIZE: 12KB
SERVER_PORT: 8080






